-- Criar tabelas
CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    data_nascimento DATE,
    nome VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE funcionario (
    id BIGINT,
    salario NUMERIC(38, 2),
    funcao VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT fk_funcionario_pessoa FOREIGN KEY (id) REFERENCES pessoa(id)
);

-- Inserir dados na tabela pessoa
INSERT INTO pessoa (id, data_nascimento, nome) VALUES (1, '2000-10-18', 'Maria');
INSERT INTO pessoa (id, data_nascimento, nome) VALUES (2, '1990-05-12', 'João');
INSERT INTO pessoa (id, data_nascimento, nome) VALUES (3, '1961-05-02', 'Caio');
INSERT INTO pessoa (id, data_nascimento, nome) VALUES (4, '1988-10-14', 'Miguel');
INSERT INTO pessoa (id, data_nascimento, nome) VALUES (5, '1995-01-05', 'Alice');
INSERT INTO pessoa (id, data_nascimento, nome) VALUES (6, '1999-11-19', 'Heitor');
INSERT INTO pessoa (id, data_nascimento, nome) VALUES (7, '1993-03-31', 'Arthur');
INSERT INTO pessoa (id, data_nascimento, nome) VALUES (8, '1994-07-08', 'Laura');
INSERT INTO pessoa (id, data_nascimento, nome) VALUES (9, '2003-05-24', 'Heloísa');
INSERT INTO pessoa (id, data_nascimento, nome) VALUES (10, '1996-09-02', 'Helena');

-- Inserir dados na tabela funcionario
INSERT INTO funcionario (id, salario, funcao) VALUES (1, 2009.44, 'Operador');
INSERT INTO funcionario (id, salario, funcao) VALUES (2, 2284.38, 'Operador');
INSERT INTO funcionario (id, salario, funcao) VALUES (3, 9836.14, 'Coordenador');
INSERT INTO funcionario (id, salario, funcao) VALUES (4, 19119.88, 'Diretor');
INSERT INTO funcionario (id, salario, funcao) VALUES (5, 2234.68, 'Recepcionista');
INSERT INTO funcionario (id, salario, funcao) VALUES (6, 1582.72, 'Operador');
INSERT INTO funcionario (id, salario, funcao) VALUES (7, 4071.84, 'Contador');
INSERT INTO funcionario (id, salario, funcao) VALUES (8, 3017.45, 'Gerente');
INSERT INTO funcionario (id, salario, funcao) VALUES (9, 1606.85, 'Eletricista');
INSERT INTO funcionario (id, salario, funcao) VALUES (10, 2799.93, 'Gerente');
